pluginManagement {
    repositories {
        maven { name = 'Aliyun Gradle Plugin'; url = 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { name = 'Aliyun Public'; url = 'https://maven.aliyun.com/repository/public' }
        gradlePluginPortal()
        maven { name = 'NeoForged'; url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
}

rootProject.name = 'net-music-pro'
